# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-29 18:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20181029_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='workflow',
            name='created',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
